import os
def writeDashboardView(nameView,nombre):
    
    fileName = "../resources/views/livewire/"+nameView+"/"+nameView+"-dashboard.blade.php"
    os.makedirs(os.path.dirname(fileName), exist_ok=True)
    file = open(fileName, "w")
    file.write('<div>\n')
    file.write('    <x-slot name="header">\n')
    file.write('        <div class="font-semibold text-xl text-gray-800 leading-tight">\n')
    file.write('            Registrar el Tipo de Beneficiario\n')
    file.write('        </div>\n')
    file.write('    </x-slot>\n')
    file.write('    <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">\n')
    file.write('        <div class="pt-10 px-10">\n')
    file.write('            <h1 class=" text-2xl font-bold">Crear tipo</h1>\n')
    file.write('        </div>\n')
    file.write('        <form wire:submit.prevent="submit" class="m-10 mt-0 p-4">\n')
    file.write('            {{-- name --}}\n')
    file.write('            <div class="mt-4 text-sm">\n')
    file.write('                Nombre\n')
    file.write('            </div>\n')
    file.write('            <x-jet-input onkeyup="this.value = this.value.toUpperCase();" type="text" placeholder="Nombre"\n')
    file.write('                wire:model="name" class="mt-1 block w-full rounded-rm" required />\n')
    file.write('            @error(\'name\')\n')
    file.write('                <p class="text-red-500 font-semibold my-2">\n')
    file.write('                    {{ $message }}\n')
    file.write('                </p>\n')
    file.write('            @enderror\n')
    file.write('            {{-- end name --}}\n')
    file.write('            {{-- descripcion --}}\n')
    file.write('            <div class="mt-4 text-sm">\n')
    file.write('                Descripción\n')
    file.write('            </div>\n')
    file.write('            <x-jet-input type="text" placeholder="Descripcion" wire:model="description"\n')
    file.write('                class="mt-1 block w-full rounded-rm" required />\n')
    file.write('            @error(\'name\')\n')
    file.write('                <p class="text-red-500 font-semibold my-2">\n')
    file.write('                    {{ $message }}\n')
    file.write('                </p>\n')
    file.write('            @enderror\n')
    file.write('            {{-- end descripcion --}}\n')
    file.write('            {{-- state --}}\n')
    file.write('            <x-jet-label class="mt-4 text-sm" value="Estado" />\n')
    file.write('            <div class="mt-4 space-y-2">\n')
    file.write('                <div class="flex items-center">\n')
    file.write('                    <input wire:model="state" value="ACTIVE" type="radio"\n')
    file.write('                        class="focus:ring-primary-500 h-4 w-4 text-primary-600 border-gray-300">\n')
    file.write('                    <label for="push_everything" class="ml-2 block text-sm font-medium text-gray-700">\n')
    file.write('                        Activo\n')
    file.write('                    </label>\n')
    file.write('                </div>\n')
    file.write('                <div class="flex items-center">\n')
    file.write('                    <input wire:model="state" value="INACTIVE" type="radio"\n')
    file.write('                        class="focus:ring-primary-500 h-4 w-4 text-primary-600 border-gray-300">\n')
    file.write('                    <label for="push_email" class="ml-2 block text-sm font-medium text-gray-700">\n')
    file.write('                        Inactivo\n')
    file.write('                    </label>\n')
    file.write('                </div>\n')
    file.write('            </div>\n')
    file.write('            {{-- end state --}}\n')
    file.write('            {{-- all errors --}}\n')
    file.write('            @if ($errors->any())\n')
    file.write('                <div class="bg-red-100 rounded-md text-red-500 p-2 font-semibold my-2">\n')
    file.write('                    <ul>\n')
    file.write('                        @foreach ($errors->all() as $error)\n')
    file.write('                            <li>{{ $error }}</li>\n')
    file.write('                        @endforeach\n')
    file.write('                    </ul>\n')
    file.write('                </div>\n')
    file.write('            @endif\n')
    file.write('            {{-- end all errors --}}\n')
    file.write('            <x-jet-button type="submit" class=" mt-4 text-sm h-12 w-full rounded-rm flex items-center justify-center">\n')
    file.write('                Guardar\n')
    file.write('            </x-jet-button>\n')
    file.write('        </form>\n')
    file.write('    </div>\n')
    file.write('</div>\n')
    file.close()
